const Data = {
    products: [
        { 
            id: '1',
            name: 'Cosmetic massage',
            description: "Cosmetic massage as a method of correcting cosmetic imperfections is essential for general cosmetic care of the skin of the face and neck." + 
            "Massage is the most effective means of preventing premature skin aging. Many cosmetic procedures will not achieve the desired effect without a combination with this type of massage.",
            image: 'face2',
            duration45: '45min',
            price45: '45£',
            duration60: '60min',
            price60: '65£',
            duration75: '75min',
            price75: '75£',
            duration90: '90min',
            price90: '90£',
        },
        { 
            id: '2',
            name: 'Anticellulite massage',
            description: "Anti-cellulite massage is a professional massage based on a combination of special techniques taken from various massage and lymphatic drainage techniques." +
            "Anti-cellulite massage is aimed at improving blood circulation, improving the structure of adipose tissue and increasing muscle tone.",
            image: 'celulite',
            duration45: '45min',
            price45: '45£',
            duration60: '60min',
            price60: '65£',
            duration75: '75min',
            price75: '75£',
            duration90: '90min',
            price90: '90£',

        },
        { 
            id: '3',
            name: 'Classical massage',
            description: "Classical massage is an effective method of prevention and complex treatment of various diseases." +
            "The effect of massage is directed mainly on the muscular system, which plays a key role in the processes of health disorders. The muscular system is the coordinating center for all aspects of health - structural, mental, chemical and energetic, realizing their close relationship.",
            image: 'classic',
            duration45: '45min',
            price45: '45£',
            duration60: '60min',
            price60: '65£',
            duration75: '75min',
            price75: '75£',
            duration90: '90min',
            price90: '90£',
        },
        { 
            id: '4',
            name: 'Massage therapy',
            description: "Therapeutic massage is a massage performed for therapeutic purposes." +
            "It has both an independent therapeutic function and an auxiliary one - enhancing the action of drugs." +
            "Therapeutic massage is used at all stages, both during treatment and after it - in the rehabilitation phase, and has practically no boundaries of application. With the help of it, diseases of the cardiovascular system, nervous system, musculoskeletal system, gastrointestinal tract, respiratory tract, metabolic disorders and many others are treated.",
            image: 'therap',
            duration45: '45 min',
            price45: '45£',
            duration60: '60 min',
            price60: '65£',
            duration75: '75 min',
            price75: '75£',
            duration90: '90 min',
            price90: '90£',
        },
        { 
            id: '5',
            name: 'Relaxing massage',
            description: " It is literally created for those who crave relaxation and bliss." +
            "During a relaxation session, you will never feel the heavy, painful and annoying actions of the masseur. Instead, there will be pleasant movements that will relax not only your muscles, but also your thoughts.",
            image: 'relax',
            duration45: '45 min',
            price45: '45£',
            duration60: '60 min',
            price60: '65£',
            duration75: '75 min',
            price75: '75£',
            duration90: '90 min',
            price90: '90£',
        },
        { 
            id: '6',
            name: 'Stone Therapy',
            description: "Stone therapy is the oldest Tibetan method of healing with heated or cooled volcanic stones. Exotic massage with hot semiprecious stones, which affects the deep mechanisms of energetic harmonization, relaxation and health." +
            "The natural energy of stones eliminates tension and stress, weakens and neutralizes negative energy, redistributes energy from areas where it is in excess to areas where it is not enough. Each stone and each color carries its own special energy, which gives a positive effect to the human body.",
            image: 'stone',
            duration45: '45 min',
            price45: '45£',
            duration60: '60 min',
            price60: '65£',
            duration75: '75 min',
            price75: '75£',
            duration90: '90 min',
            price90: '90£',
        },
        { 
            id: '7',
            name: 'Lymphatic drainage massage',
            description: "Lymphatic drainage massage is one of the most demanded massage methods. And it is not difficult to explain such popularity - after the course you will notice far more than one positive effect. Strengthening immunity, removing fluid from the body, getting rid of extra centimeters - the list of advantages does not end there. Plus, the process itself is very relaxing and is a great way to end your day. We describe all the benefits, types and methods of performing lymphatic drainage massage below.",
            image: 'lymph',
            duration45: '45 min',
            price45: '45£',
            duration60: '60 min',
            price60: '65£',
            duration75: '7 5min',
            price75: '75£',
            duration90: '90 min',
            price90: '90£',
        },
        { 
            id: '8',
            name: 'Aromatherapy',
            description: "Aromatherapy is one of the methods of traditional medicine that helps in the healing, prevention and treatment of various diseases using essential oils. The essence lies in the treatment with the aromas of various plants, which are really capable of having a serious effect on the human body, and not only on his mood. For the human body, aromatherapy can be carried out through the penetration of aromatic substances through the respiratory tract, mucous membranes and skin.But at the same time, absolutely all vegetable essential oils, subject to the correct dosage, do not have a negative effect on the body, do not cause addiction and reduce the effectiveness of the effect.",
            image:'aroma',
            duration45: '45min',
            price45: '45£',
            duration60: '60min',
            price60: '65£',
            duration75: '75min',
            price75: '75£',
            duration90: '90min',
            price90: '90£',
        },

    ]
}

export default Data;